ApkController/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topic/', views.topics, name='topics'),
    path('topic/<topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<topic_id>)/', views.new_entry, name='new_entry'),
    path('edit_entry/<entry_id>)/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""定义users的URL模式"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """用户学习主题"""
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的关于某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    data_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + '...'

users/models.py
from django.db import models


# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.

def index(request):
    """学习笔记主页"""
    return render(request, "learning_logs/index.html")


@login_required()
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-data_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据，创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据，创建一个新表单
        form = EntryForm()
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate


# Create your views here.


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录并重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-topics" href="{% url 'learning_logs:topics' %}">Topics <span
                        class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-righ">
            {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.&nbsp&nbsp&nbsp</a></li>
                <li><a href="{% url 'users:logout' %}">Log Out</a></li>
            {% else %}
                <li><a href="{% url 'users:register' %}">Register&nbsp&nbsp&nbsp</a></li>
                <li><a href="{% url 'users:login' %}">Log In</a></li>
            {% endif %}

        </ul>
    </div>

</nav>
<div class="container">
    <div class="page-header">
        {% block header %}
            <br/>
            <br/>
        {% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>

</div>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}

    <h4>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h4>
    <h4>Edit entry:</h4>
    <form class="form" action="{% url 'learning_logs:edit_entry' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <div class="jumbotron">
        <h3>Track your learning</h3>
    </div>
    <h4>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
    </h4>

    <h4>
        Whenever you learn something new about a topic, make an entry summarizing
        what you've learned.
    </h4>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <h4>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h4>
    <h4>Add a new entry:</h4>
    <form class="form" action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <h4>Add a new topic:</h4>
    <form class="form" action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}

        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <h4> {{ topic }}</h4>
    <p><a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a></p>
    {% for entry in entries %}
        <div class="card">
            <div class="card-header">
                <h4>
                    {{ entry.data_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h4>
            </div>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <h4>Topics</h4>
    <ul>
        {% for topic in topics %}
            <li>
                <h5>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h5>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <h5>
        <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
    </h5>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}



{% block content %}

    <h4>Log in to your account.</h4>

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again</p>
    {% endif %}
    <form class="form" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">login in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}

    <h4>Register a new account.</h4>

    <form class="form" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>

{% endblock content %}